[versions]
loom = "1.0.+"
loom_quiltflower = "1.7.+"

minotaur = "2.4.+"
cursegradle = "2.+"
github_release = "2.+"
machete = "1.+"

minecraft = "1.19.3"
yarn = "3"
fabric_loader = "0.14.11"
fabric_api = "0.69.1+1.19.3"
yacl = "2.1.1"
mod_menu = "5.0.0"
mixin_extras = "0.1.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
mixin_extras = { module = "com.github.llamalad7:mixinextras", version.ref = "mixin_extras" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
